name: "AfterRefactor"
description: "This config checks if the experimental setup is working as intended from the software side. The device is a 8 terminal RNPU in a 2 terminal configuration, with one electrode being current driven and swept from -150nA to 150nA following Wilfreds waveform, and the other being on readout via NI DAC modules. All other 6 electrodes are supplied with a static control voltage."

min_value: -150e-9
max_value: 150e-9
data_density: 30
voltage_range: [-3, 3]
current_range: [-0.01, 0.01]
amplification: 28
ramp_points: 30

nidaq:
  activation_module_id: 'cDAQ1Mod1'
  readout_module_id: 'cDAQ1Mod2'
  sample_frequency: 10000.0
  update_frequency: 1000.0
  samples_per_measurement: 5
  readout_channels: [0, 1, 2, 3, 4, 5, 6, 7] # 0-7
  control_voltages:
    0: 1
    1: 2
    2: 1.5
    3: 2.5
    4: -1
    5: -2
    6: -1.5
    7: -2.5

smu:
  device_id: 'GPIB0::15::INSTR'
  timeout: 50000
  drive_mode: 'CURRENT_DRIVEN'
  tolerance_voltage: 0.01
  tolerance_current: 10e-9
  pause_between_set: 0.02