name: "VI_NIDAQ_ONLY_13O_6I"
description: "Test Run on DNPU to check Device Connectivety"

min_value: -1.5
max_value: 1.5
data_density: 30
voltage_range: [-3, 3]
current_range: [-0.2e-6, 0.2e-6]
amplification: 28
ramp_points: 1000

nidaq:
  activation_module_id: 'cDAQ1Mod1'
  readout_module_id: 'cDAQ1Mod2'
  sample_frequency: 10000.0
  update_frequency: 1000.0
  samples_per_measurement: 5
  readout_channels: [13] # 0-7
  control_voltages:
    1: 1.2
    2: 0.4
    3: -1.2
    4: -0.4
    5: 0.5
    14: -1
    15: -1
    6: -0.5
    9: -0.5
    8: 1.25
    13: 1.33


smu:
  device_id: 'GPIB0::15::INSTR'
  timeout: 50000
  drive_mode: 'VOLTAGE_DRIVEN'
  tolerance_voltage: 0.01
  tolerance_current: 10e-9
  pause_between_set: 0.02