name: "NGR Proof"
description: "This shows that the RNPU still shows NGR."

min_value: -1.2
max_value: 1.2
data_density: 30
voltage_range: [-3, 3]
current_range: [-0.01, 0.01]
amplification: 28
ramp_points: 1000

nidaq:
  activation_module_id: 'cDAQ1Mod1'
  readout_module_id: 'cDAQ1Mod2'
  sample_frequency: 10000.0
  update_frequency: 1000.0
  samples_per_measurement: 5
  readout_channels: [] # 0-7
  control_voltages:
    5: 0
    9: -0.70795244
    8: -0.99676251
    13: -0.69912177
    14: 0.72853076
    15: -0.63085985
    6: -0.30407035


smu:
  device_id: 'GPIB0::15::INSTR'
  timeout: 50000
  drive_mode: 'CURRENT_DRIVEN'
  tolerance_voltage: 0.01
  tolerance_current: 10e-9
  pause_between_set: 0.02